#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

'''
   {note}

'''

def load(obj):
    obj.{name} = {name}

def {name}(self):
    url = 'http://music.163.com'
    params = {
      "csrf_token": ''
    }
    return self.post(url, None, params)
